### PR TITLE
Move locale files to standard location.

### LINKED ISSUE #603: You can not change language
```
You can not change the language even though they are available. The program is 
still in English.

Error can be repeated as follows.

*choose it: Edit > preferences > language
*change language
*restart keepnote

- System Information:
Debian Release: wheezy/sid
  APT prefers unstable
  APT policy: (500, 'unstable')
Architecture: i386 (i686)

Kernel: Linux 3.2.0-2-686-pae (SMP w/1 CPU core)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash

Versions of packages keepnote depends on:
ii  libsqlite3-0   3.7.11-3
ii  python         2.7.2-10
ii  python-glade2  2.24.0-3
ii  python-gtk2    2.24.0-3
ii  python2.6      2.6.7-4
ii  python2.7      2.7.3~rc2-2.1

keepnote recommends no packages.

Versions of packages keepnote suggests:
pn  python-gnome2-extras  <none>

-- no debconf information

```

Original issue reported on code.google.com by `kha...@elfathi.fr` on 3 May 2012 at 8:57

### PR DESCRIPTION
**Pull request by bdabelow**
Should fix #603 #572

### CODE REVIEW

**Comment by bdabelow** [comment]
Messed, will open new pull request.

**Comment by bdabelow** [comment]
Messed up, will create new pull request.

**Comment by mdrasmus** [comment]
Sorry I missed this before. If you make a new PR, I'll review.

**Comment by bdabelow** [comment]
Recreated as #721.

**Pull request closed without merging**
